creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    # This would normally be just the staging key, but we're using a dev key for this example
    key_groups:
      - age:
          # David Fairbrother
          - age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
