apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
components:
  - ../../../components/capi-addons
  - ../../../components/capi-infra

patches:
  # Ensure overlay points to self
  - target:
      kind: Application
      name: cloud-deployed-apps
    path: "patch_overlay_path.yaml"
  # ... and for the infra too
  - target:
      kind: ApplicationSet
      name: cluster-appset
    path: "patch_infra_location.yaml"
