creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    # All developers can access / edit secrets on dev
    key_groups:
      - age:
          # David Fairbrother
          - age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
          # Dev Argo Key
          - age1g8yqmzjqpgmu4x5acfpc8a2ud8n8886c5wu5mw5ac2qel6ldq5fsgaf89t
